#### TotalRecall ###
services:
  nextjs: #### NextJS et Prisma ###
    image: node:18-alpine
    container_name: nextjs
    working_dir: /app
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - mongo
    command: ["sh", "-c", "npx next dev & npx prisma studio"]

  mongo:  #### MongoDB ###
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js
      - ./mongo_backup:/data/ ## Pour sauvegarder les données dans le répertoire mongo_backup
    command: --replSet rs0

volumes:
  mongo-data: